### ISSUE TITLE
Problem: Images not displayed in Chrome in a grid

### ISSUE THREAD

**Issue by erancha** [aautio/react-modal-image#22] opened 2019-12-05 09:03 UTC
git clone https://github.com/erancha/test-modal-image.git
npm i
npm start
------------------
Please refer to https://github.com/erancha/test-modal-image/blob/master/src/Viewer.js :
/* Line #11:
        <ModalImage key={index} small={image} large={image} alt={index} />
            - is functional in FF and Edge, but no images are displayed in Chrome (Google Chrome is up to date Version 78.0.3904.108 (Official Build) (64-bit)).
            - in Chrome, the image height (as seen in 'Inspect element') is 0; only after un-checking 'max-height', does the image display ..
        <img key={index} src={image} alt={image} height='75' width='75' />
            - is functional in all browsers.
*/

**Comment by aautio** [comment] 2022-09-09 14:13
I'm unable to reproduce this. Closing.

**Closed by aautio** 2022-09-09 14:13 UTC
